### PR TITLE
Add support for devices with MinimumValue/MaximumValue/StepValue constraints

### PR DESCRIPTION
**Pull request by cannikin**
First off let me just say that I LOVE THIS GEM. I went from having no idea how to get my own devices on Homekit, to having an actual device on Homekit in the span of a couple of hours. Thank you!!

The only hiccup I came across was trying to add a Window Covering. I was getting this error:

```
2019-06-06 14:18:34 - KeyError - key not found: "ValidValues":
	/Users/rob/.gem/ruby/2.5.1/gems/ruby_home-0.2.0/lib/ruby_home/hap/values/uint8_value.rb:16:in `fetch'
	/Users/rob/.gem/ruby/2.5.1/gems/ruby_home-0.2.0/lib/ruby_home/hap/values/uint8_value.rb:16:in `valid_values'
	/Users/rob/.gem/ruby/2.5.1/gems/ruby_home-0.2.0/lib/ruby_home/hap/values/uint8_value.rb:12:in `first_default_value'
	/Users/rob/.gem/ruby/2.5.1/gems/ruby_home-0.2.0/lib/ruby_home/hap/values/uint8_value.rb:6:in `default'
	/Users/rob/.gem/ruby/2.5.1/gems/ruby_home-0.2.0/lib/ruby_home/hap/values/base_value.rb:17:in `value'
	/Users/rob/.gem/ruby/2.5.1/gems/ruby_home-0.2.0/lib/ruby_home/characteristic.rb:78:in `value'
	/Users/rob/.gem/ruby/2.5.1/gems/ruby_home-0.2.0/lib/ruby_home/http/serializers/characteristic_serializer.rb:34:in `value_hash'
	/Users/rob/.gem/ruby/2.5.1/gems/ruby_home-0.2.0/lib/ruby_home/http/serializers/characteristic_serializer.rb:17:in `record_hash'
	/Users/rob/.gem/ruby/2.5.1/gems/ruby_home-0.2.0/lib/ruby_home/http/serializers/object_serializer.rb:23:in `block in serializable_hash'
	/Users/rob/.gem/ruby/2.5.1/gems/ruby_home-0.2.0/lib/ruby_home/characteristic_collection.rb:10:in `each'
	/Users/rob/.gem/ruby/2.5.1/gems/ruby_home-0.2.0/lib/ruby_home/characteristic_collection.rb:10:in `each'
```

I did some digging and found that when adding a device like a Fan, the constraints will look something like:

```ruby
{"ValidValues"=>{"0"=>"Open", "1"=>"Closed", "2"=>"Opening", "3"=>"Closing", "4"=>"Stopped"}}
```

But the constraints for Window Covering look like:

```ruby
{"MaximumValue"=>100, "MinimumValue"=>0, "StepValue"=>1}
```

So I tweaked the `valid_values` method to first try `ValidValues` and if that returns `nil` then look for `MiniumumValue` and `MaximumValue` and create the same type of hash where the key is the valid value (every value between `MiniumumValue` and `MaximumValue` by `StepValue`):

```ruby
{"0"=>"0", "1"=>"1", "2"=>"2", "3"=>"3", "4"=>"4", "5"=>"5", "6"=>"6", "7"=>"7", "8"=>"8", "9"=>"9", "10"=>"10", "11"=>"11", "12"=>"12", "13"=>"13", "14"=>"14", "15"=>"15", "16"=>"16", "17"=>"17", "18"=>"18", "19"=>"19", "20"=>"20", "21"=>"21", "22"=>"22", "23"=>"23", "24"=>"24", "25"=>"25", "26"=>"26", "27"=>"27", "28"=>"28", "29"=>"29", "30"=>"30", "31"=>"31", "32"=>"32", "33"=>"33", "34"=>"34", "35"=>"35", "36"=>"36", "37"=>"37", "38"=>"38", "39"=>"39", "40"=>"40", "41"=>"41", "42"=>"42", "43"=>"43", "44"=>"44", "45"=>"45", "46"=>"46", "47"=>"47", "48"=>"48", "49"=>"49", "50"=>"50", "51"=>"51", "52"=>"52", "53"=>"53", "54"=>"54", "55"=>"55", "56"=>"56", "57"=>"57", "58"=>"58", "59"=>"59", "60"=>"60", "61"=>"61", "62"=>"62", "63"=>"63", "64"=>"64", "65"=>"65", "66"=>"66", "67"=>"67", "68"=>"68", "69"=>"69", "70"=>"70", "71"=>"71", "72"=>"72", "73"=>"73", "74"=>"74", "75"=>"75", "76"=>"76", "77"=>"77", "78"=>"78", "79"=>"79", "80"=>"80", "81"=>"81", "82"=>"82", "83"=>"83", "84"=>"84", "85"=>"85", "86"=>"86", "87"=>"87", "88"=>"88", "89"=>"89", "90"=>"90", "91"=>"91", "92"=>"92", "93"=>"93", "94"=>"94", "95"=>"95", "96"=>"96", "97"=>"97", "98"=>"98", "99"=>"99", "100"=>"100"}
```

And then the code that comes after that can behave as before—pull the first key and convert it to an integer and return it as the default value.

If there is a third kind of Value constraint that we don't know about yet this will blow up again. Let me know if you'd like me to make it a little more foolproof (maybe raise a custom error if neither `ValidValue` or `MinimumValue` are found in the constraint?)

### CODE REVIEW

**Comment by karlentwistle** [comment]
@cannikin thanks for the kind words! It's always really nice to know someone is getting value out of the gem 😄 Also thanks for this fantastic PR it made it really easy for me to get up to speed with the examples you shared.

I've dug into it a bit as well and it looks like the only uint8 combination I'd covered was

```
:format: uint8
:unit: nil
```

https://github.com/karlentwistle/ruby_home/blob/master/lib/ruby_home/config/characteristics.yml#L19

However, as you said and shared there is also

```
:format: uint8
:unit: percentage
```

https://github.com/karlentwistle/ruby_home/blob/master/lib/ruby_home/config/characteristics.yml#L109

With that in mind, it would be fantastic if you could add a test for the behaviour you've uncovered. Something like:

```ruby
require 'spec_helper'

RSpec.describe RubyHome::Uint8Value do
  describe '#default' do
    context 'unit nil' do
      it 'returns first default value from ValidValues' do
        template = double(constraints: { 'ValidValues' => { '0' => 'Inactive' } } )
        handler = RubyHome::Uint8Value.new(template)
        expect(handler.default).to eql(0)
      end
    end

    context 'unit percentage' do
      it 'returns first default value MinimumValue' do
        template = double(constraints: { 'MaximumValue' => 100, 'MinimumValue' => 0, 'StepValue' => 1} )
        handler = RubyHome::Uint8Value.new(template)
        expect(handler.default).to eql(0)
      end
    end
  end
end
```
 
https://github.com/karlentwistle/ruby_home/blob/master/spec/lib/hap/values/uint8_value_spec.rb

The way you've implemented this `(min..max).step(step) { |n| values[n.to_s] = n.to_s }` is really cool. It seems like we only care about the `default_value` though so I'm not sure the current implementation would ever use any of the other values that are being generated.

So I kind of wonder if we'd get away with something like this

```ruby
def range_values
  min = template.constraints.dig('MinimumValue')
  {min.to_s => min}
end
```

If we ever wanted to add some validations etc then your approach would be better because we'd have a lookup table to make sure we're dealing with a valid value. It's just that at the moment we're generating all those values and then only using the first one. What do you think?

> If there is a third kind of Value constraint that we don't know about yet this will blow up again. Let me know if you'd like me to make it a little more foolproof (maybe raise a custom error if neither ValidValue or MinimumValue are found in the constraint?)

If you don't mind/have the time to add this that would be fantastic and greatly appreciated. It would probably save a fellow developer sometime in the future as well. I should have probably added in some error messages myself 😅  

Thanks again for taking the time to write up this PR. Really appreciated!

**Comment by cannikin** [comment]
You're welcome! 

I added the full range of values `(min..max).step(step) { |n| values[n.to_s] = n.to_s }` thinking that maybe there was some validation going on between incoming values and the possible values in the constraint, but for now if this is *only* concerned about the default I'll definitely simplify that.

Yeah I realized last night as I was falling asleep that I hadn't added any tests to that code! 😅I'll get those added. And I'll see about that custom error as well!

**Comment by cannikin** [comment]
@karlentwistle Updated with all suggestions! Also bumped the version to 0.2.1.

**Comment by karlentwistle** [comment]
That's awesome, thanks very much!

**Pull request merged**
